function model = fnc_jointCoord_PatellaR (model,DoF_Types)
% Bone Mesh Female Toolkit 
% Licensed under the zlib license. See LICENSE for more details.

jointCenter_patellaR_global = ...
    model(6).vertices_global(model(6).LandmarkIndices(1),:);
jointAxes_patellaR_global           = eye(4);
jointAxes_patellaR_global(1:3,4)    = jointCenter_patellaR_global;
jointAxes_patellaR_in_femurR = [[jointAxes_patellaR_global(1:3,1:3)'*...
    model(4).joint_axes_global(1:3,1:3)] ...
    [jointCenter_patellaR_global'-model(4).joint_axes_global(1:3,4)];...
    0 0 0 1];
jointAxes_patellaR_in_femurR(1:3,1:3) = eye(3);
model(6).joint_axes_global          = jointAxes_patellaR_global;
model(6).joint_axes_local           = jointAxes_patellaR_in_femurR;
model(6).parentID                   = 4;
model(6).joint                      = [];
model(6).vertices_centered = model(6).vertices_global -...
    repmat(median(model(6).vertices_global),...
    length(model(6).vertices_global), 1);
model(6).mesh_offset = [-min(model(6).vertices_centered(:,1))*0.5...
    -min(model(6).vertices_centered(:,2))*0.2...
    -min(model(6).vertices_centered(:,3))*0.9];