function model = fnc_jointCoord_PatellaL (model,DoF_Types)
% Bone Mesh Female Toolkit 
% Licensed under the zlib license. See LICENSE for more details.

jointCenter_patellaL_global = ...
    model(7).vertices_global(model(7).LandmarkIndices(1),:);
jointAxes_patellaL_global           = eye(4);
jointAxes_patellaL_global(1:3,4)    = jointCenter_patellaL_global;
jointAxes_patellaL_in_femurL = [[jointAxes_patellaL_global(1:3,1:3)'*...
    model(5).joint_axes_global(1:3,1:3)]...
    [jointCenter_patellaL_global'-model(5).joint_axes_global(1:3,4)];...
    0 0 0 1];
jointAxes_patellaL_in_femurL(1:3,1:3) = eye(3);
model(7).joint_axes_global          = jointAxes_patellaL_global;
model(7).joint_axes_local           = jointAxes_patellaL_in_femurL;
model(7).parentID                   = 5;
model(7).joint                      = [];
model(7).vertices_centered = model(7).vertices_global -...
    repmat(median(model(7).vertices_global),...
    length(model(7).vertices_global), 1);
model(7).mesh_offset = [-min(model(7).vertices_centered(:,1))*0.5...
    min(model(7).vertices_centered(:,2))*0.2 -...
    min(model(7).vertices_centered(:,3))*0.9];