function model = fnc_jointCoord_FibulaR (model,DoF_Types)
% Bone Mesh Female Toolkit 
% Licensed under the zlib license. See LICENSE for more details.

jointCenter_fibulaR_global         =...
    model(10).vertices_global(model(10).LandmarkIndices(1),:);
jointAxes_fibulaR_global           = eye(4);
jointAxes_fibulaR_global(1:3,1:3)  = model(8).joint_axes_global(1:3,1:3);
jointAxes_fibulaR_global(1:3,4)    = jointCenter_fibulaR_global;
jointAxes_fibulaR_in_tibiaR = [[jointAxes_fibulaR_global(1:3,1:3)'*...
    model(8).joint_axes_global(1:3,1:3)]...
    [jointCenter_fibulaR_global'-model(8).joint_axes_global(1:3,4)];...
    0 0 0 1];
model(10).joint_axes_global        = jointAxes_fibulaR_global;
model(10).joint_axes_local         = jointAxes_fibulaR_in_tibiaR;
model(10).parentID                 = 8;
model(10).joint                    = [];
model(10).vertices_centered        = model(10).vertices_global -...
    repmat(median(model(10).vertices_global),...
    length(model(10).vertices_global), 1);
model(10).mesh_offset = [0.0 0.0...
    min(model(10).vertices_centered(:,3))*0.9];